#!/usr/bin/env bash

function syntax_error {
  echo "Syntax error. Use -h or --help for options"
  exit 2
}

function help_message {
  echo "A bash wrapper for wttr.in."
  echo "Displays weather forecast for a location, or the current phase of the moon."
  echo "Options:"
  echo "  -3, --3day:      Get the full, 3-day forecast"
  echo "  -c, --city CITY: Specify the location city as CITY, e.g. -c Berlin"
  echo "  -m, --moon:      Show the moon phase (location agnostic)"
  echo "Without any options, it will return a 1 day forecast for your current location"
  exit 4
}

OPTSPEC=":hmc3-:"

while getopts "$OPTSPEC" optchar; do
  case "${optchar}" in
    -)
      case "${OPTARG}" in
        help)
          help_message
          ;;
        moon)
          moon=true
          ;;
        3day)
          three=true
          ;;
        city)
          nodisplaylocation=true
          city="${!OPTIND}"
          OPTIND="$(( OPTIND + 1 ))"
          ;;
        *)
          syntax_error
          ;;
      esac
      ;;
    h)
      help_message
      ;;
    m)
      moon=true
      ;;
    3)
      three=true
      ;;
    c)
      nodisplaylocation=true
      city="${!OPTIND}"
      OPTIND="$(( OPTIND + 1 ))"
      ;;
    *)
      syntax_error
      ;;
  esac
done

if [[ $three && $moon = true ]]; then
    echo "The 3-day and moon phase views are mutually exclusive; please choose one or the other"
    exit 4
fi

# In awk processes below, xt and xh are lines to exclude from the head and tail of curl output, respectively
# Should be slightly more portable than using head and tail
# To extract tail, awk builds a buffer and begins printing it only after NR>xt e.g. a[1] is printed when a[xt] is being recorded

if  [[ $three = true ]]; then
  curl -s http://wttr.in/$city 2> /dev/null | awk -v xt=2 '{if(NR>xt) print a[NR%xt]; a[NR%xt]=$0}'
elif [[ $moon = true ]]; then
  curl -s http://wttr.in/moon 2> /dev/null | awk -v xt=4 '{if(NR>xt) print a[NR%xt]; a[NR%xt]=$0}'
elif [[ $nodisplaylocation = true ]]; then
  curl -s http://wttr.in/$city 2> /dev/null | awk -v xt=33 '{if(NR>xt) print a[NR%xt]; a[NR%xt]=$0}' | awk -v xh=1 'NR>xh{print $0}'
  echo ""
else
  curl -s http://wttr.in/ 2> /dev/null | awk -v xt=33 '{if(NR>xt) print a[NR%xt]; a[NR%xt]=$0}'
  echo ""
fi
