#!/bin/bash
#check if getopt works
getopt --test > /dev/null
if [[ $? -ne 4 ]]; then
    echo "getopt does not work in this environment"
    exit 1
fi

function help_message {
    echo "This is a wrapper for wttr.in"
    echo "-3, --3-day: Get the full, 3-day forecast"
    echo "-c, --city: Specify the city, wttr.in will predict otherwise"
    echo "-m, --moon: Show the moon phase"
    echo "Without any options, it will return a 1 day forecase with location prediction"
}

#create options for getopt
SHORT=3c:hm
LONG=3-day,city:,help,moon
PARSED=`getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"`

if [[ $? -ne 0 ]]; then
    exit 2
fi

eval set -- "$PARSED"

while true; do
    case "$1" in
        -h|--help)
            help_message
            exit 4
            ;;
        -m|--moon)
            moon=true
            shift
            break
            ;;
        -c|--city)
            location="$2"
            shift 2
            ;;
        -3|--3-day)
            three=true
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Error"
            exit 3
            ;;
    esac
done

if [[ $three && $moon = true ]]; then
    echo "Please only use one view option"
    exit 4
fi

if  [[ $three = true ]]; then
    curl -s http://wttr.in/$location 2> /dev/null | head -n -2
elif [[ $moon = true ]]; then
    curl -s http://wttr.in/moon 2> /dev/null | head -n -4
else
    curl -s http://wttr.in/$location 2> /dev/null | head -7 | tail -6
    echo ""
fi
